language: java
jdk:
- oraclejdk8

services:
- postgresql

addons:
postgresql: "9.6.2"

before_script:
- psql -c "CREATE DATABASE test_ranking;" -U postgres
- psql -c "CREATE DATABASE ranking;" -U postgres
- psql -c "CREATE USER myuser WITH PASSWORD 'postgres';" -U postgres
- export DATABSE_URL="jdbc:postgresql://localhost/ranking?user=myuser&password=postgres&ssl=false"
- export TEST_DATABSE_URL="jdbc:postgresql://localhost/test_ranking?user=myuser&password=postgres&ssl=false"

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: lol-ranking