language: java
jdk:
- oraclejdk8

services:
- postgresql

addons:
  postgresql: "9.5"

before_script:
- psql -c "CREATE DATABASE test_ranking;" -U postgres
- psql -c "CREATE DATABASE ranking;" -U postgres
- psql -c "CREATE USER myuser WITH PASSWORD 'postgres';" -U postgres

script:
- mvn clean install -B

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: lol-ranking
